name: CI-CD with AWS ECR
on: { push: { branches: [main] } }
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: \${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: \${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: \${{ secrets.AWS_REGION }}
    - run: |
        aws ecr get-login-password --region \${{ secrets.AWS_REGION }} |
        docker login --username AWS --password-stdin \${{ secrets.ECR_REPO }}
    - run: |
        docker build -t flask-ci-cd-app .
        docker tag flask-ci-cd-app:latest \${{ secrets.ECR_REPO }}:latest
        docker push \${{ secrets.ECR_REPO }}:latest
